FROM node:20-alpine

RUN npm install -g http-server

WORKDIR /usr/src/app

COPY ../aplicacion .

EXPOSE 8080

CMD ["http-server", "-p", "8080", "-c-1", "-d", "false", "-a", "0.0.0.0", "-o", "snake.html"]