# .github/workflows/build-dev.yml

name: Build and Push Dev Image

on:
  push:
    branches: [ main ]
    paths:
      - 'dev/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Construir imagen dev
        run: docker build -t tomasbeltran/egi_cloud:latest -f ./dev/Dockerfile-dev .

      - name: Login a Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Subir imagen a Docker Hub
        run: docker push tomasbeltran/egi_cloud:latest
