name: Build and Push Test Image

on:
  push:
    branches: [ main ]
    paths:
      - 'test/**'
      - 'aplicacion/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Build imagen test (única por commit)
        run: docker build -t tomasbeltran/egi_cloud:${{ github.sha }} -f ./test/Dockerfile-test .

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push imagen test
        run: docker push tomasbeltran/egi_cloud:${{ github.sha }}
